### PR TITLE
Use the PhotoMessageModel Template instead of Protocol

### PR DESCRIPTION
**Pull request by allaire**
Inline with how `TextMessageViewModel` is built.

Maybe I'm missing something about why we need the computed property with the underscore property combo?

Thanks!

### CODE REVIEW

**Comment by allaire** [comment]
@diegosanchezr Diago could you shed some lights on why the PhotoMessageViewModel has the underscore / computed property and not the TextMessageViewModel? https://github.com/badoo/Chatto/commit/da05cb2a09a46f5f5dc7680446fefc148c4f7cd8#diff-dc2adbf0ccead4d01e8f4ee15f83694d

**Comment by allaire** [comment]
@AntonPalich Any idea why we must use `_photoMessage` to access our photoMessageTemplate ?

**Comment by AntonPalich** [comment]
@allaire I don't know exact reason, but I beleive it is related to a property named `messageModel` that is defined in a different protocols with different types. DemoPhotoMessageViewModel conforms to all those protocols.

If you check the failed build you will see a compilation error in the demo app in `DemoPhotoMessageViewModel.swift:71`. If you change `self._photoMessageModel` with `self.photoMessageModel` it will compile in Swift 4. My assumption that it couldn't compile with previous Swift versions. This code was written using Swift 2.

In Badoo we don't use this generic photo view model, we implemented our own view model that conforms to `PhotoMessageViewModelProtocol` (I don't know exact reason why it was done like this). So, those changes are pretty safe for us, but they may break other apps. This if fine, just need to be mentioned in CHANGELOG. I'll do it when release new Chatto version

**Comment by allaire** [comment]
@AntonPalich Thanks! It makes sense that it wasn't compiling in previous Swift versions.

Great for the Changelog, I'm going to close it then :)

**Pull request closed without merging**
