### PR TITLE
Use resource_bundles

### PR DESCRIPTION
**Pull request by phatmann**
Fixes issue #613

### CODE REVIEW

**Comment by wiruzx** [comment]
Hey @phatmann 

Thanks a lot for the PR!

I've tried to run tests in your branch and I had a crash.

Could you please check that?

Screenshot 2019-10-07 at 09 45 28

**Comment by phatmann** [comment]
My fix should have allowed resource bundles to be in framework or in test bundle. That is why tests are crashing. I am not using Chatto anymore so I cannot justify spending time to make this change. Hopefully you can do so to make the tests pass.

**Comment by wiruzx** [comment]
@phatmann I see, I'll try to figure it out then. Thanks a lot anyway!

**Comment by wiruzx** [comment]
Fixed in #686

**Pull request closed without merging**
