### PR TITLE
Swift 4 support (some modifications)

### PR DESCRIPTION
**Pull request by jpunz**

### CODE REVIEW

**Comment by AntonPalich** [comment]
@jpunz I've created swift4 branch and changed base branch to it. I'll take a look into changes. However they're won't be merged into master until Xcode 9 GM version is released.

Thank you for your help!

**Comment by AntonPalich** [comment]
@geegaset Please, take it into account

**Comment by jpunz** [comment]
That's fine, would make no sense if you push it to main branch, because swift 4 isn't supported by cocoapod at the moment.

**Comment by irace** [comment]
Can this please be merged into `swift4`? 🙏

**Pull request closed without merging**
