### PR TITLE
Add updating logic to text message

### PR DESCRIPTION
**Pull request by maxkonovalov**
Added support for `willBeShown()` and `wasHidden()` functions in `TextMessageViewModel`. The main purpose of this is to give chance to the client to load the avatar images when needed. Most of the code was copied from the corresponding functions in `PhotoMessagePresenter`.
Both Text and Photo message models now look pretty similar, so maybe you guys consider moving some parts to the base classes?

Also added the missing `observe` calls for the avatar image in view models.

And the essential part of this commit is the call to the main queue in `updateClosure`:
```swift
dispatch_async(dispatch_get_main_queue(), {
    self?.updateCurrentCell()
})
```
It looks strange, but if you try to set the observable value in `willBeShown()`, although the model itself has been updated, in `BaseMessageCollectionViewCell.updateViews()` it still gets the old value, so the update has no visible effect. Deferring the update with an async call to the main queue seems to fix the issue here.

### CODE REVIEW

**Comment by diegosanchezr** [comment]
Hi @maxkonovalov,

Yes, I think we should move the avatar thing to the BaseMessagePresenter and clean the text and photo ones a little bit. We would appreciate if you do this here (not required).

I was tracking down your need for the dispatch_async. Check the root cause here: https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20160711/002580.html. If you don't mind, could you make Observable a class and remove the dispatch_async?

Thank you!

**Comment by maxkonovalov** [comment]
Hey @diegosanchezr, sorry for the delay, sure, I'll try add these changes as soon as possible.

**Comment by diegosanchezr** [comment]
Hi @maxkonovalov, are you still able to work on this? We'd definitely like to merge this. Thank you!

**Comment by maxkonovalov** [comment]
Hey @diegosanchezr, sorry again - very busy with my other projects, but will get back to this issue in a few days!

**Comment by diegosanchezr** [comment]
Cool, thank you!

**Comment by maxkonovalov** [comment]
Hey @diegosanchezr! As requested, I updated the `Observable` - it now seems to work without issues.

For refactoring, I only moved the declarations of the methods `willBeShown()` and `wasHidden()` to their common protocol. I think it may still be worth combining `TextMessageViewModel` and `PhotoMessageViewModel` to some common superclass instead of inheriting both from a protocol.

Also changed the avatar show/hide logic, because the previous implementation triggered `Observable` updates resulting in infinite loop.

**Comment by diegosanchezr** [comment]
@maxkonovalov Thank you!

**Pull request merged**
