### PR TITLE
Use binarySearch algorithm in layoutAttributesForElements(in rect: CGRect)

### PR DESCRIPTION
**Pull request by SlavinskiySergey**
Inspired by [Tour of UICollectionView](https://developer.apple.com/videos/play/wwdc2018/225)

### CODE REVIEW

**Comment by AntonPalich** [comment]
@SlavinskiySergey Thanks for this PR! Sorry that it takes time to approve it. We will test how it work and will proceed soon.

**Comment by SlavinskiySergey** [comment]
@AntonPalich glad to help! 

To compare execution time I used below func:
`@discardableResult
  func measure<A>(name: String = "", _ block: () -> A) -> A {
    var info = mach_timebase_info()
    guard mach_timebase_info(&info) == KERN_SUCCESS else { return block() }

    let start = mach_absolute_time()
    //Block execution to time!
    let result = block()
    let end = mach_absolute_time()

    let elapsed = end - start

    let nanos = elapsed * UInt64(info.numer) / UInt64(info.denom)
    let timeElapsed = TimeInterval(nanos) / TimeInterval(NSEC_PER_SEC)
    print("Time: \(name) - \(timeElapsed))")
    
    return result
}`

**Comment by SlavinskiySergey** [comment]
@AntonPalich any news from testing perspective?

**Comment by AntonPalich** [comment]
@SlavinskiySergey Thanks for contribution!

**Pull request merged**
