### PR TITLE
Some fixes on Xcode 8.1

### PR DESCRIPTION
**Pull request by alexsanderkhitev**

### CODE REVIEW

**Comment by diegosanchezr** [comment]
Hi @alexsanderkhitev, can you elaborate a little bit about this PR? master branch compiles fine for me and others as is in Xcode 8.1

**Comment by alexsanderkhitev** [comment]
Hi @diegosanchezr I get these errors in Xcode 8.1 

There are errors in the KeyboardTracker

```
  private override var intrinsicContentSize: CGSize {
        return self.preferredSize
    }
```
Xcode prefers to do so
```
 fileprivate override var intrinsicContentSize: CGSize {
        return self.preferredSize
    }
```
Another example 
https://monosnap.com/file/iahSCbXe0pu6uj7XhKgb2pWHr9eZat

**Comment by alexsanderkhitev** [comment]
@diegosanchezr  I'm surprised that you didn't get this error in the Xcode 8.1.

**Comment by diegosanchezr** [comment]
ah, you're trying to compile the latest release. This was solved in https://github.com/badoo/Chatto/pull/233

I'm waiting for Travis to install Xcode 8.1 to release Chatto 3.0.1. Until that you can point to master branch

**Comment by alexsanderkhitev** [comment]
@diegosanchezr thank you for your answer =)

**Pull request closed without merging**
