### PR TITLE
Pagination batchUpdates instead of reload

### PR DESCRIPTION
**Pull request by GrigoryUlanov**
Hello!
I found that when update mode is equal to pagination, all collection view is reloading. I think that it is not so productive. It is better to use batch Updates but without animation.

### CODE REVIEW

**Comment by diegosanchezr** [comment]
Hi @GrigoryUlanov, I tried this before and decided to use reloaData because it showed to be more efficient in my tests.

**Comment by GrigoryUlanov** [comment]
@diegosanchezr, may be full reloading gives better tests, but I'm using Chatto now and I had a problem where because of reload all cells, text was flicker. It was not very beautiful..

**Comment by diegosanchezr** [comment]
Do you have a reproducer for this flickering?

**Comment by GrigoryUlanov** [comment]
I have video where you can see this bug reproduction.
ezgif com-video-to-gif

**Comment by diegosanchezr** [comment]
That looks like some dispatch_async that prevents the cells from being configured when they should - instead, the recycled version is shown until it gets reconfigured

**Pull request closed without merging**
